meal_plans/urls.py
from django.urls import path
from meal_plans.views import (
    MealPlanCreateView,
    MealPlanUpdateView,
    MealPlanDeleteView,
    MealPlanDetailView,
    MealPlanListView,
)


urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plans"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plans_detail"),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plans_delete",
    ),
    path("new/", MealPlanCreateView.as_view(), name="meal_plans_new"),
    path(
        "<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_plans_edit"
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("meal_plans/", include("meal_plans.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.
class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField(
        "recipes.Recipe", related_name="meal_plans"
    )

meal_plans/forms.py
from django.forms import ModelForm
from meal_plans.models import MealPlan

# mealPlanForm
class MealPlanForm(ModelForm):
    class Meta:
        model = MealPlan
        fields = ["name", "date", "recipes"]


# mealPlanDeleteForm


class MealPlanDeleteForm(ModelForm):
    class Meta:
        model = MealPlan
        fields = []

meal_plans/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from meal_plans.models import MealPlan
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required

# from meal_plans.forms import MealPlanForm, MealPlanDelete
from meal_plans.models import MealPlan

# Create your views here.


class MealPlanListView(ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate = 10

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self):
        return reverse_lazy("meal_plans_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ meal_plans }}"?</p>
        {{ form.as_p }}
        <div class="control">
            <button class="button">Delete</button>
        </div>
    </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}


{% block content %}
<main class="tag-detail">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
    <div>
        <a href="{% url 'meal_plans_edit' mealplan.pk %}">Edit</a>
        <a href="{% url 'meal_plans_delete' mealplan.pk %}">Delete</a>
    </div>
    <h2> Recipes for {{ mealplan.name }} on {{ mealplan.date }} </h2>
    {% for recipe in mealplan.recipes.all %}
    <p>
        <a href="{% url 'recipe_detail' recipe.id %}">{{ recipe }}</a>
    </p>
    {% endfor %}
</main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Update</button>
        </div>
    </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}


{% block content %}
<main class="recipe-grid">
    {% for mealplan in mealplan_list %}
    <div class="recipe-card">
        <h2 class="recipe-card-title">
            <a href="{% url 'meal_plans_detail' mealplan.pk %}">{{ mealplan.name }}</a>
        </h2>
        <p class="recipe-card-date">{{ mealplan.updated }}</p>
    </div>
    {% endfor %}
</main>
{% endblock content %}
{% block pagination %}
<footer>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1"> First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Back</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        </span>
    </div>
</footer>
{% endblock pagination %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}